UI showing Queue list and Contract Store
CyberNano/dollar_token pull request #24
Opened 2017-03-10 08:26 UTC by chatch

2017-03-10 22:13 UTC, gnidan commented on app/config.json
> +        "endpoint": "http://?.?.?.?:8545"
Since the truffle.js relies on hostnames following the scheme in gnidan/docker-eth-dev, should the dapp part be set up that way as well?

2017-03-13 10:13 UTC, chatch commented on app/config.json
> +        "endpoint": "http://?.?.?.?:8545"
yes that makes sense. i'll change it to use the truffle.js then.

2017-03-13 22:38 UTC, gnidan commented
@chatch I believe this could use the existing truffle service in docker-compose.

I'm going to see about [adding IPFS support](https://github.com/gnidan/docker-eth-dev/issues/11) to my repo and then this should be a non-issue to switch hostnames around.

I'd like to try this out locally and play with it before I'd feel comfortable reviewing

2017-03-16 03:31 UTC, chatch commented on app/config.json
> +        "endpoint": "http://?.?.?.?:8545"
@gnidan I've made this change now. See app.js I'm pulling client host from truffle.js. I had to remove the default builder from truffle.js as I get errors on import in app.js. I think it doesn't matter and the default builder gets set anyway? In any case i'm using webpack seperatly to build. Let me know if it all looks okay.

2017-03-16 03:32 UTC, chatch commented
@gnidan This is ready for a (re)review now. Can you take a look at latest changes. Major things are:

- updated to use truffle.js host as per your comment above
- updates to contracts view - now shows BVC details in table
- merged in all of latest master branch

2017-03-16 03:34 UTC, gnidan requested changes
Just requesting the truffle.js change, the config.json looks nice! (Although we might have to figure out a dynamic services address later)

2017-03-16 03:34 UTC, gnidan commented on app/javascripts/app.js
> +const netConfig = truffleJs.networks[config.network]
oh, nice!

2017-03-16 03:34 UTC, gnidan commented on truffle.js
> +            host: "52.221.123.6",
Assuming these got changed by accident? I don't think those IPs are static at all, or portable. did you have trouble with the hostnames?

2017-03-16 03:36 UTC, gnidan commented
Other than that, looks good!

2017-03-16 03:39 UTC, gnidan approved these changes
bam!

2017-03-16 03:40 UTC, chatch commented on truffle.js
> +            host: "52.221.123.6",
oops. yes i've just changed these back!

2017-03-16 03:42 UTC, chatch commented
thanks mate!

2017-03-16 03:42 UTC, merged